from ..models import model_loader
from .vector_db import vector_db_service

class LLMService:
    """
    This class encapsulates the core Retrieval-Augmented Generation (RAG) logic.
    It connects the language model, the embedding model, and the vector database.
    """
    def __init__(self):
        # The models are loaded once by the ModelLoader singleton
        self.llm_pipeline = model_loader.llm_pipeline
        self.tokenizer = model_loader.tokenizer
        # The vector DB service provides the retriever
        self.retriever = vector_db_service.get_retriever()

    def answer_query(self, query: str) -> str:
        """
        Answers a user's query using the RAG pipeline.
        1. Retrieves relevant context from the vector database.
        2. Constructs a detailed prompt with the context and query.
        3. Generates a response using the language model.
        """
        print(f"Received query for LLM Service: {query}")

        # 1. Retrieve relevant context
        relevant_docs = self.retriever.get_relevant_documents(query)
        context = "\n\n".join([doc.page_content for doc in relevant_docs])
        print("Retrieved context from vector database.")

        # 2. Create the prompt using the model's chat template
        messages = [
            {
                "role": "system",
                "content": "You are an expert assistant for telecommunications standards. Answer the user's question based ONLY on the provided context. If the context doesn't contain the answer, state that you don't have enough information."
            },
            {
                "role": "user",
                "content": f"CONTEXT:\n{context}\n\nQUESTION:\n{query}"
            }
        ]

        prompt = self.tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True
        )

        # 3. Generate the response
        print("Generating response from LLM...")
        outputs = self.llm_pipeline(
            prompt,
            max_new_tokens=512,
            do_sample=True,
            temperature=0.7,
            top_p=0.95,
        )

        # The answer is the part generated by the assistant
        generated_text = outputs[0]["generated_text"]
        answer = generated_text[len(prompt):].strip()

        print("Response generated.")
        return answer

# Create a singleton instance of the service that can be imported elsewhere
llm_service = LLMService()